# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: deploy on staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: contention/rsync-deployments@v2.0.0
        with:
          FLAGS: -avzr --delete
          EXCLUDES: --exclude .git --exclude .github
          USER: ${{ secrets.DEPLOY_USER }}
          HOST: ${{ secrets.DEPLOY_HOST }}
          LOCALPATH: /
          REMOTEPATH: ${{ secrets.DEPLOY_DIR }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}